"""Markdown reporter — a clean assessment write-up that renders on GitHub."""

from __future__ import annotations

from ..models import ScanReport, Severity

_SEV_BADGE = {
    "Critical": "🔴 Critical",
    "High": "🟠 High",
    "Medium": "🟡 Medium",
    "Low": "🔵 Low",
    "Informational": "⚪ Informational",
}


def _fence(text: str, limit: int = 600) -> str:
    t = text.strip()
    if len(t) > limit:
        t = t[:limit] + "\n…(truncated)"
    return t


def build(report: ScanReport) -> str:
    counts = report.severity_counts()
    lines: list[str] = []
    lines.append(f"# LLM Security Assessment — {report.target}")
    lines.append("")
    lines.append(f"- **Standard:** {report.standard}")
    lines.append(f"- **Assessor:** {report.assessor}")
    lines.append(f"- **Scanned:** {report.scanned_at}")
    lines.append(f"- **Overall posture:** **{report.posture()}**")
    lines.append(
        f"- **Probes:** {report.vulnerable_count} vulnerable / {len(report.probes)} run"
    )
    lines.append("")

    # Summary table.
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("| --- | --- |")
    for sev in Severity:
        lines.append(f"| {_SEV_BADGE[sev.value]} | {counts[sev.value]} |")
    lines.append("")

    lines.append("| Probe | OWASP | Severity | Result |")
    lines.append("| --- | --- | --- | --- |")
    for p in report.probes:
        result = "❌ VULNERABLE" if p.vulnerable else "✅ passed"
        sev = _SEV_BADGE[p.severity.value] if p.vulnerable else "—"
        lines.append(f"| `{p.probe_id}` {p.name} | {p.owasp.value} | {sev} | {result} |")
    lines.append("")

    # Detailed findings — only for probes that fired.
    findings = [p for p in report.probes if p.vulnerable]
    if findings:
        lines.append("## Findings")
        lines.append("")
        for i, p in enumerate(findings, 1):
            lines.append(f"### {i}. {p.name}  `{p.probe_id}`")
            lines.append("")
            lines.append(f"- **OWASP:** {p.owasp.value}")
            lines.append(f"- **Severity:** {_SEV_BADGE[p.severity.value]}")
            lines.append("")
            lines.append(p.description)
            lines.append("")
            ex = p.vulnerable_attempts[0]
            lines.append("**Proof of concept**")
            lines.append("")
            lines.append("_Attack prompt:_")
            lines.append("")
            lines.append("```text")
            lines.append(_fence(ex.prompt))
            lines.append("```")
            lines.append("")
            lines.append(f"_Model response_ ({ex.note}):")
            lines.append("")
            lines.append("```text")
            lines.append(_fence(ex.response))
            lines.append("```")
            lines.append("")
            if p.remediation:
                lines.append(f"**Remediation:** {p.remediation}")
                lines.append("")
            if p.references:
                lines.append("**References:** " + ", ".join(p.references))
                lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        lines.append("No vulnerabilities confirmed — the target passed every probe. ✅")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by [llm-security-toolkit](https://github.com/usmanzia-ux/llm-security-toolkit)._"
    )
    return "\n".join(lines)


def render(report: ScanReport, output: str) -> str:
    with open(output, "w", encoding="utf-8") as fh:
        fh.write(build(report))
    return output
